C言語ファイルの実行・結果出力に対応
o-tofu7741/scoring-assistant pull request #16
Opened 2024-09-23 16:56 UTC by maysay-D

### 概要
- `.gitignore`
   - C言語関連のファイルとmacOSが自動生成するファイルを追加しました。
- `answer.py`
   - C言語のファイルが`settings.json`内に書かれていた際に、 C言語のファイルをgccでコンパイルし、実行・出力結果の書き出しを行うプログラムを加筆しました。
- `main.py`
   -  gccが出力した実行ファイル（`*.out`）を採点終了後に削除するようにしました。
- `README.md`
   - C言語の対応について明記しておきました。
   - その他、オブジェクト指向言語の時にライブラリのインストールに戸惑っていた様子だったので、必要そうな外部ライブラリなども明記しておきました。
- `test`ディレクトリ内
   - `settings.json` 
      - C言語のファイルを実行し、出力結果を書き出すために加筆しました。
   - `.c`ファイル系統
      - 第二回小レポート課題の答案をもとに、合っているものを`user-01`ディレクトリに、コンパイル上で警告が出るものを`user-02`ディレクトリに配置しました。

2024-09-26 03:40 UTC, o-tofu7741 requested changes
resultのファイルについては修正おなしゃす🙏

どこで削除するとかの話は気分でお任せ〜

2024-09-26 03:40 UTC, o-tofu7741 commented on test/report-12345/result.txt
> +java.io.FileNotFoundException: /home/yuta/github/scoring-assistant/test/share/phones.csv (No such file or directory)
絶対パスで指定した俺の環境由来のファイルでテストしちゃってるねこれ

2024-10-03 17:53 UTC, maysay-D commented on main.py
> +    # *.outファイルを削除
`main.py`内で一括で削除する方法は、万が一途中で実行エラーが起きた際に、ファイルがディレクトリ内に中途半端に残ってしまい、少々面倒なことになると後から考えたので、`answer.py`内で、実行した都度適宜削除することにしました。

2024-10-03 17:55 UTC, maysay-D commented on test/report-12345/result.txt
> +java.io.FileNotFoundException: /home/yuta/github/scoring-assistant/test/share/phones.csv (No such file or directory)
`settings.json`内の`"name": "PhoneNumbers.java"`にある`"args_value"`を絶対パスから相対パスの`"../../../share/phones.csv"`にすることでこの点を解決しました。

2024-10-03 18:05 UTC, maysay-D commented
レビューを踏まえて、以下を修正しました。
- `*.out`ファイルの削除処理を`main.py`から`answer.py`に移行
   - 全てが実行し終わった後に一気に削除する、という方法で処理を行うのではなく、ひとつひとつのプログラムを実行した都度削除することにしました。
- `settings.json`内、`"name": "PhoneNumbers.java"`の`"args_value"`で指定されているパスを絶対パスから相対パスに修正
   - `"../../../share/phones.csv"`に修正し、`FileNotFoundException`が起きないようにしました。

2024-10-04 00:56 UTC, o-tofu7741 approved these changes

2024-10-04 00:57 UTC, merged